version: '3.9'
services:
  server:
    build: ./pikpak-plus-server
    ports:
    - '5000:5000'
    volumes:
    - ./pikpak-plus-server:/app
    environment:
      FLASK_APP: prod
    env_file:
        - ./.env
  web:
    build: ./pikpak-plus-client
    ports:
      - '3001:3001'
    volumes:
    - ./pikpak-plus-client:/user/src/app
    env_file:
        - ./.env